### ISSUE TITLE
Active Sessions page renders first page after update

### ISSUE THREAD

**Issue by rosstimothy** [gravitational/webapps#1062]
The Active Sessions page periodically refreshes the list of sessions from the web api. After getting the updated list of sessions the sessions table is refreshed and always returns to the first page. This makes scrolling through the pages almost impossible if you have a large number of sessions. By the time you get to page N and try to locate a session, the update process kicks in and you are sent back to the first page.

**Comment by zmb3** [comment]
This is one of the only pages I'm aware of that implements its own polling to automatically refresh.  

Should we just remove the polling and require a manual refresh? Or add a dedicated reload button?

**Comment by zmb3** [comment]
This was recently fixed with #1196
