### ISSUE TITLE
Hide `teleport.internal` labels from the UI

### ISSUE THREAD

**Issue by hatched** [gravitational/webapps#1081]
`teleport.internal/` labels are used to power various Teleport features. Modifying them or relying on them for RBAC purposes can break things, so we should hide these labels from the UI.

**Comment by sielakos** [comment]
Hi @hatched 

I have a few questions about it:
1. Exactly what entity?
2. How to reproduce it?

**Comment by hatched** [comment]
So this issue may not be necessary any longer. The new cluster alerts feature was at one point going to have labels on Servers containing the alert message but ultimately it went another direction. 

We probably should still filter those labels but at the moment I don't know of a situation where it would be problematic.

**Comment by zmb3** [comment]
We should still hide `teleport.internal` labels from the UI.

You can reproduce this by creating a any resource (an SSH node, for example) with a label key prefixed by `teleport.internal/`. For example: `teleport.internal: test`.

**Comment by sielakos** [comment]
@zmb3 @jimbishopp 
Should we always hide ``teleport.internal`` for all methods including ``tsh`` and ``tctl``?
I have a quick fix, but it's rather universal:

Before fix:

```bash
root@go:/app# tctl nodes ls
Host         UUID                                 Public Address  Labels                 Version
------------ ------------------------------------ --------------- ---------------------- ----------
749df7b60ade 0760c6af-a54e-49f4-abd8-e5ad1dbacb6a 172.20.0.7:3022 teleport.internal=test 11.0.1
node         bf77f03d-76ac-4f31-ad87-427f3ce31126                 hostname=node          12.0.0-dev
```

After fix:

```bash
root@go:/app# tctl nodes ls
Host UUID                                 Public Address Labels        Version
---- ------------------------------------ -------------- ------------- ----------
node bf77f03d-76ac-4f31-ad87-427f3ce31126                hostname=node 12.0.0-dev
```

Not sure if we want to go this way? If not I will need to add a new optional filter to ListResourceRequest.

**Comment by zmb3** [comment]
Yes, you can hide them from tsh and from the web UI. Remember, it's any label with a `teleport.internal/` key prefix. So `teleport.internal/foo` should be hidden as well.

**Comment by sielakos** [comment]
@zmb3 Based on your comment I have prepared a new approach on the client side (gRPC client side). I have described my thinking in a comment to PR. Do you think it is the right way to go?
