### ISSUE TITLE
Suggest removing "$" from the code examples

### ISSUE THREAD

**Issue by eddiejaoude** [gravitational/webapps#1154]
When using the GitHub copy button, in the code blocks, it includes `$` which causes the command to fail.

Removing the `$` would fix this.

```
$ yarn build-teleport-oss
```

to be

```
yarn build-teleport-oss
```

<img width="991" alt="Screenshot 2022-08-27 at 10 36 55" src="https://user-images.githubusercontent.com/624760/187024603-229359bd-8009-48b6-9e7a-a1fe74b63c0b.png">

**Comment by Rounak-28** [comment]
can I work on this?
