### ISSUE TITLE
Update Create a Support Ticket URL

### ISSUE THREAD

**Issue by travelton** [gravitational/webapps#1239]
https://github.com/gravitational/webapps/blob/4580cf234dc66b9f58af559b556ad62dd021c4fb/packages/teleport/src/Support/Support.tsx#L66

Please adjust this URL. Additionally, linking directly to `https://support.goteleport.com` is preferred, versus linking to the form page. 

```
url="https://support.goteleport.com" 
```

Note: We have migrated off of Zendesk. We have temporary redirects in place for now.

**Comment by zmb3** [comment]
@rudream would you mind taking care of this one when you get a moment? Should be quick. Backport to 11, 10, 9, and 8.
