### ISSUE TITLE
Improve Invalid Web Session UX

### ISSUE THREAD

**Issue by travelton** [gravitational/webapps#130]
### Description

**What happened**:
Given an active session in Teleport Web UI, if the session becomes invalid, there's no easy way to clear the session and gain access to the login screen. Instead, you have to go to your browser's cookies and local storage to clear them in order to restore the login screen. 

**What you expected to happen**:
When a `403 Forbidden` is returned from any webapi endpoints, the UX should lead the user to a solution (i.e. redirect to login screen, attempt re-authentication). 

**How to reproduce it (as minimally and precisely as possible)**:
1. From a fresh Teleport Cluster, create a new user, login to the Teleport Web UI, and access the dashboard/home screen. 
2. From the auth server, run `tctl users rm <your user>`. 
3. Observe the result in the Teleport Web UI. There's no way to get out of this problem unless you clear both the local storage `grv_teleport_token` key and the `session` cookie. 

![image](https://user-images.githubusercontent.com/241714/88859140-c8bc5a80-d1be-11ea-8d0f-00e3358f4d49.png)

### Environment
- Teleport version (use `teleport version`): Teleport Enterprise v4.3.2git:v4.3.2-0-gc6d702ad8 go1.13.2
- Tsh version (use `tsh version`): N/A, used web console
- OS (e.g. from `/etc/os-release`): Ubuntu 16.0.4

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): GCP

**Browser environment**

- Browser Version (for UI-related issues): Chrome 84.0.4147.89

**Comment by travelton** [comment]
Created a video showing the problem. https://drive.google.com/file/d/1kzEntBIFP2Zi_E3cG2m4OocHutjEXQ1r/view?usp=sharing

**Comment by alex-kovoy** [comment]
This error does not indicate that web session became invalid (see the successful 'status' checks). This is an internal server error coming from internal authorization layers.

closing it in favor of https://github.com/gravitational/teleport/issues/4204
