### ISSUE TITLE
Refactor teleport useAttempt

### ISSUE THREAD

**Issue by kimlisa** [gravitational/webapps#132]
#### Description
Currently, in `useAttempt().run()`,we throw when our callback fails, which allows the original caller to catch this error too if they want to do additional handling. 

Handling error at the original caller side is optional and currently, we do not use this feature in any of our code. Not using this feature poses these problems:

- not catching the throw fails test 
- unnecessary unhandled promise rejection error logs in browser

Because it is a feature we don't use, we should remove it and the errors that may cause from not handling:
Line to remove: https://github.com/gravitational/webapps/blob/master/packages/shared/hooks/useAttempt.ts#L66

This removable requires to review all uses of `useAttempt().do()` and make necessary changes to prevent bugs eg: the `then` block of this code, will always run: https://github.com/gravitational/webapps.e/blob/master/gravity/src/cluster/components/License/UpdateLicenseDialog/UpdateLicenseDialog.jsx (move it inside to fix this)

**Comment by alex-kovoy** [comment]
it's been addressed in [useAttemptNext](https://github.com/gravitational/webapps/blob/master/packages/shared/hooks/useAttemptNext.ts)
