### ISSUE TITLE
[teleport] Rename variable names

### ISSUE THREAD

**Issue by kimlisa** [gravitational/webapps#134]
#### Description
Rename the following to remove ambiguity:

- [x] rename `cfg.clusterName` to `leafCluster` in teleport/config.ts, and everywhere it is used
- [x] rename `storeUser` to `storeUserContext` in teleport/teleportContext.ts and everywhere it is used

**Comment by Being-Maverick** [comment]
Hey @kimlisa , I would like to work on this. Please assign it to me.

**Comment by kimlisa** [comment]
Hi @Being-Maverick! Thank you for your interest and offer of help, but we currently have some branches that are already addressing this issue indirectly, so this issue has to wait until that branch merges with master.

**Comment by alex-kovoy** [comment]
it's obsolete. Closing it.
