### ISSUE TITLE
Can't install locally, gravitational/webapps.e repo isn't accessible

### ISSUE THREAD

**Issue by Tchekda** [gravitational/webapps#1378]
Hi, 

I'm trying to build teleterm but it included gravitational/webapps.e which isn't public anymore.

Even from the [github page](https://github.com/gravitational/webapps/tree/master/packages) the subodule link doesn't work anymore.

Kinda problematic to make it work.

Any help would be appreciated. 

Thx

**Comment by gzdunek** [comment]
We would like to fix the issue as soon as possible, in the meantime you can use the patch from here: https://github.com/gravitational/teleport/issues/17706 

I'm closing this issue in favor of the linked one.
