### ISSUE TITLE
[teleport] Touchups

### ISSUE THREAD

**Issue by kimlisa** [gravitational/webapps#156]
- [x] increase page limit to 50 from 7 for session recordings
- [x] loading indicators on users/authconn/roles are not consistent. They should be like the rest (to be displayed on the first half of the screen)
- add missing commits
  - [x] auth type column in users

- [x] Search on the "Session Recordings" screen does not work

- [x] Feature "Users" does not check for  ACL.users.list access https://github.com/gravitational/webapps/blob/stratus/packages/teleport/src/features.ts#L302
- [x] Fixed broken sorting on the "name" column in the "Users" table

**Comment by alex-kovoy** [comment]
closed by https://github.com/gravitational/webapps/issues/156
