### ISSUE TITLE
Teleport V5: Style SideNav 

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/webapps#159]
Below design is based on the early version of the new teleport UI and does not match 1 to 1 with what we currently have. This is expected. The colors and the font sizes need to be adjusted on the below image, please work with the UX team to get the correct values for these parameters.

Make sure that the tabbing works as expected.

![image](https://user-images.githubusercontent.com/7816406/94367251-84a8e180-00ab-11eb-8897-885d3a9807f7.png)

**Comment by alexwolfe** [comment]
this pull request addresses this ticket. https://github.com/gravitational/webapps/pull/168

**Comment by alex-kovoy** [comment]
done
