### ISSUE TITLE
curl script command for node join needs -f adding

### ISSUE THREAD

**Issue by webvictim** [gravitational/webapps#177]
![image](https://user-images.githubusercontent.com/897821/96497603-51c4ba00-1221-11eb-9cac-e2c1d8938c34.png)

Sorry I didn't notice this earlier. The `curl` command here should start with `curl -fsSL` rather than `curl -sSL` (to ensure that curl explicitly fails if there is a problem)

**Comment by alex-kovoy** [comment]
@webvictim when we return the bash error script we also set HTTP error code. The `-f` flag will prevent the bash error script from running.  So I think in this case we should not return the error code in the first place. The generic bash script with the error message and `exit 1` at the end would do the job. 

@kimlisa could you do the following?

1. Add the `-f` flag
2. Change the install-node-sh endpoint so it does not set the error code on HTTP header.
