### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by yixjuan** [gravitational/webapps#217]
1.git clone webapps
2.cd webapps
3.yarn install
4.yarn build-teleport
<img width="801" alt="图片" src="https://user-images.githubusercontent.com/68119885/105277513-865c5f00-5bde-11eb-8180-be22e9940bf0.png">

5.yarn build-gravity
alway run `yarn build-gravity && yarn build-gravity-e` then error
<img width="415" alt="图片" src="https://user-images.githubusercontent.com/68119885/105277247-07ffbd00-5bde-11eb-87cd-5dbdb68c6883.png">
<img width="1026" alt="图片" src="https://user-images.githubusercontent.com/68119885/105277402-51e8a300-5bde-11eb-968b-1c1cbd97a98b.png">

we want to use teleport's build in our own project,we copy the output in dist to our project, but the app.js doesn't send POST request to `siteSessionPath: '/v1/webapi/sites/:siteId/sessions',` Is it because teleport's build was fail in the end，so the output in dist is also wrong?

**Comment by alex-kovoy** [comment]
@yixjuan  To build only open source version please use below command 

```
$ yarn build-teleport-oss
$ yarn build-gravity-oss
```

**Comment by alex-kovoy** [comment]
@yixjuan i've updated our readme file.

Btw, you can also run a dev server against your teleport backend by running below command

```
$ yarn start-teleport-oss --target=https://example.com:3080/web
```

**Comment by yixjuan** [comment]
Thank you,it works well!
