### ISSUE TITLE
Grammar fixes for Teleport Cloud UI

### ISSUE THREAD

**Issue by ulysseskan** [gravitational/webapps#224]
On the Roles page, `Learn more in cluster management (RBAC) section` should be `Learn more in **the** cluster management (RBAC) section` https://github.com/gravitational/webapps/blob/076b228b0357f4a1b7748d313cb914b0156cc1dd/packages/teleport/src/Roles/Roles.tsx#L106

Perhaps debatable, but on the Trusted Clusters page, `Trusted Clusters allows Teleport administrators to connect multiple clusters together` should be `Trusted Clusters **allow** Teleport administrators to connect multiple clusters together` 
PR: https://github.com/gravitational/webapps/pull/223

**Comment by ulysseskan** [comment]
To be clear, #223 doesn't yet fix the Roles.tsx error.

**Comment by webvictim** [comment]
(pretty sure it does now)
