### ISSUE TITLE
Update Download links to Download page.

### ISSUE THREAD

**Issue by benarent** [gravitational/webapps#243]
Since RBAC is in OSS, we no longer require Enterprise binaires and can use the OSS clients. We are also using v6.0.0 `https://get.gravitational.com/teleport-ent-v6.0.0-darwin-amd64-bin.tar.gz`, if we do keep it we should keep this up to date. 

![image](https://user-images.githubusercontent.com/559288/110826491-fafc6300-8249-11eb-8c7d-a03625b2a2e3.png)

**Comment by alex-kovoy** [comment]
done (both versions reference the same binaries now)
