### ISSUE TITLE
Empty Node Name, Session Recordings Table

### ISSUE THREAD

**Issue by travelton** [gravitational/webapps#246]
With Teleport running in "Proxy Recording Mode", the `session.end` events fired from Teleport lack the server_hostname. See #[4146](https://github.com/gravitational/teleport/issues/4146) for more details. 

In the interim, can we please include a default value? The empty value looks bad.

I believe the culprit is this line [here](https://github.com/gravitational/webapps/blob/master/packages/teleport/src/Recordings/RecordList.tsx#L128):

```
let hostname = raw.server_hostname || "Unknown";
```

Unavailable or N/A are other options.

**Comment by travelton** [comment]
@alex-kovoy Thoughts? This is causing some turmoil with a customer so wanted to propose a temporary solution.

**Comment by alex-kovoy** [comment]
@travelton we will use `N/A` as a default value.
