### ISSUE TITLE
[DB Access 5] Add Button and Popup Dialogue

### ISSUE THREAD

**Issue by kimlisa** [gravitational/webapps#273]
# Add Button and Popup Dialogue
Add a button to the main component (as shown in the table image below), that depending:

- [x] If is enterprise, and is root cluster, check that user has permission to create, and show `Add Database` btn, that on click shows a dialogue with manual instructions to add database (as shown in image)
  - [x] If a user can't create, do not show a button 
- [x] if is enterprise, and is a leaf cluster, show disabled button `Adding a database to a leaf cluster is not supported`  
- [x] if its os, show a button `View Documentation` that leads to our docs on database

Even if not stated in the issue (won't be from now on :), if applicable, create stories, test it works (if applicable update it in `Main.story`), and create tests

### Button Design
![image](https://user-images.githubusercontent.com/43280172/115493893-6b1ee100-a219-11eb-98a5-46b525a569c3.png)

### Manual instructions to add a database
Very similar to `Apps` component, but with more steps. Step 4 should be a drop down menu with `isSearchable` flag set to true.
```
Redshift PostgreSQL
Cloud SQL PostgreSQL
Self-hosted PostgreSQL
Self-hosted MySQL
RDS/Aurora PostgreSQL
RDS/Aurora MySQL
```
Depending on user selection, step 5 CLI command field value will change.

Step 5 CLI Template (TODO, double check this is the correct template, updates are coming for this command): 
```
* angle brackets mean we fill it out for user
* square brackets mean user has to fill out themselves

teleport start --roles=db --token=[generated-join-token] --auth-server=<hostname> --db-name=[db-name] --db-protocol=<protocol> --db-type=<type> --db-uri=[db-uri]
```
![image](https://user-images.githubusercontent.com/43280172/115627057-3ceddf80-a2b3-11eb-8369-e26971db375f.png)

### Tip
- Export these flags from your custom hook so you can easily manipulate them for stories
- Test integration in OS `Main.story` and Enterprise `Main.story`, interact with the button, make sure dialogue pops up onClick, can close it onClose, etc.

**Comment by r0mant** [comment]
## Database agent start command examples

### Self-hosted Postgres

```bash
teleport start \
   --roles=db \
   --token=[token] \
   --auth-server=proxy.example.com:443 \
   --db-name=[name] \
   --db-protocol=postgres \
   --db-uri=[uri]
```

### Self-hosted MySQL

```bash
teleport start \
   --roles=db \
   --token=[token] \
   --auth-server=proxy.example.com:443 \
   --db-name=[name] \
   --db-protocol=mysql \
   --db-uri=[uri]
```

### RDS Postgres

```bash
teleport start \
   --roles=db \
   --token=[token] \
   --auth-server=proxy.example.com:443 \
   --db-name=[name] \
   --db-protocol=postgres \
   --db-uri=[uri] \
   --db-aws-region=[region]
```

### RDS MySQL

```bash
teleport start \
   --roles=db \
   --token=[token] \
   --auth-server=proxy.example.com:443 \
   --db-name=[name] \
   --db-protocol=mysql \
   --db-uri=[uri] \
   --db-aws-region=[region]
```

### Redshift Postgres

```bash
teleport start \
   --roles=db \
   --token=[token] \
   --auth-server=proxy.example.com:443 \
   --db-name=[name] \
   --db-protocol=postgres \
   --db-uri=[uri] \
   --db-aws-region=[region] \
   --db-aws-redshift-cluster-id=[cluster ID]
```

### Cloud SQL Postgres

```bash
teleport start \
   --roles=db \
   --token=[token] \
   --auth-server=proxy.example.com:443 \
   --db-name=[name] \
   --db-protocol=postgres \
   --db-uri=[uri] \
   --db-ca-cert=[instance CA file path] \
   --db-gcp-project-id=[project ID] \
   --db-gcp-instance-id=[instance ID]
```
