### ISSUE TITLE
[Downloads 1] Create a tab switch component

### ISSUE THREAD

**Issue by kimlisa** [gravitational/webapps#308]
## Description
Create a tab switch component with tab contents containing download CLI commands for different OS. We will use the same instructions as found here for now: https://goteleport.com/docs/getting-started/#step-1-install-teleport-on-a-linux-host

We want our tab switch component to work similary to the link i stated above, except our coloring/styling/display should match as the image shown below.

The source code for the tab switch component that is used in our docs, can be found in our next repo: https://github.com/gravitational/next (as reference and example).

I recommend running its storybook and playing with it before you start.

This component should go under `Downloads` directory in our enterprise submodule.

## Screenshot
![image](https://user-images.githubusercontent.com/43280172/118046477-3ee51480-b32e-11eb-9051-304ce72b2148.png)

**Comment by alex-kovoy** [comment]
@kimlisa the code from the `next` repo should be used as an example/reference. It's OK to copy&past but it should use our theme and design package (plus, it needs to go through a proper code review).
