### ISSUE TITLE
[Teleterm] Use Teleport icon to display Terminal process in system dock

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/webapps#433]
When Terminal starts, it should use company branded icons for a system dock (instead of default ones). Note that icon format differs between operation systems: linux, mac, and windows. 

![image](https://user-images.githubusercontent.com/7816406/138891017-4815f661-7ffc-4bdf-899f-3c4ee9f0c5a5.png)

**Comment by zmb3** [comment]
@gzdunek can we close this one?

**Comment by gzdunek** [comment]
The icon will be changed probably, but I think we can close this task
