### ISSUE TITLE
teleport ui not works on localhost

### ISSUE THREAD

**Issue by pwn33d** [gravitational/webapps#553]
hello guys when i try run docker this problem face me any solution?
34 assets
1002 modules
webpack 5.64.4 compiled successfully in 31592 ms
/var/www/html/labs/webapps/node_modules/http-proxy/lib/http-proxy/index.js:120
    throw err;
    ^

xxx
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1138:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '93.xxx.xxx.34',
  port: 3080
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/bin/node
Arguments: /usr/local/lib/node_modules/yarn/lib/cli.js start --target=https://example.com:3080/web
Directory: /var/www/html/labs/webapps/packages/teleport
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by ibeckermayer** [comment]
What Docker command did you use?

**Comment by alex-kovoy** [comment]
closing (stale)
