### ISSUE TITLE
Make the `DesktopPlayer`'s progress bar progression smoother

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/webapps#579]
### `SESSION_END`
The current `PlayerClientEvent.SESSION_END` listener in `DesktopPlayer.tsx` causes the progress bar to jump abruptly to the end of the session if the session was sitting without any events happening for a while before being ended. (e.g. if a user got an error screen, sat there reading it for 10 seconds, and then ended the session.) 

We can solve this by adding logic for calculating the difference between durationMs and prevState.current, and then updating state on a regular interval until we reach durationMs.

### In General
The `SESSION_END` problem described above generalizes to the whole playback -- at any point in a recorded session, the user might have been sitting doing nothing and the screen not changing, and so we won't be getting any events back over the websocket. During those times, the progress bar isn't moving, even though in reality time is progressing. 

Note that the best solution may include modifying the backend.

### `requestAnimationFrame`
We may be able to make the progress bar smoother in general by getting the [throttle logic](https://github.com/gravitational/webapps/blob/4c87011b0245b412a25614a0467a996d6bcdc123/packages/teleport/src/Player/DesktopPlayer.tsx#L72-L84) to make use of `requestAnimationFrame`.

**Comment by zmb3** [comment]
@ibeckermayer what was the PR that fixed this?

**Comment by ibeckermayer** [comment]
It was https://github.com/gravitational/webapps/pull/648
