### ISSUE TITLE
Copy/paste issue in Teleport Web Console

### ISSUE THREAD

**Issue by travelton** [gravitational/webapps#92]
### Issue:
When using the Teleport Web Console, and attempting to copy/paste a string that exceeds the length of the console window, xterm.js inserts a line break between the wrapped lines. This breaks any output that may be a URL. You need to copy and paste the output in to a text editor, remove the line breaks, then copy/paste in your browser. This issue does not occur on a native terminal. 

### Repro Steps:
```
$ echo 'http://www.google.com/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' > test.txt

$ cat test.txt
http://www.google.com/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaa
```
### Potential Fix:
This issue was fixed in xterm.js v2.8.0 via https://github.com/xtermjs/xterm.js/pull/693. It [appears](https://github.com/gravitational/webapps/blob/master/packages/teleport/package.json#L22) we are currently on version v2.4.0.

**Comment by benarent** [comment]
It looks like X-Term has improved a lot since the 2.x times, with current being 4.x. Any reason to not just bump version?  We should at least consider upgrading to 2.9.2 for extra bug fixes.

**Comment by alex-kovoy** [comment]
@benarent, never versions have some API changes which need to be addressed on our side. 
For example, newly versions have some issues when unwinding the session in the player. But I agree that it's about time to update it. If anything, we can use 2 versions: one for session player and another for active sessions.

As for this bug fix, we can do the following:

1. Use [our fork](https://github.com/gravitational/xterm.js) and create a branch 2.8.0.
2. Packport [this commit](https://github.com/gravitational/xterm.js/commit/ebffd9370bc3882856d92a8887d7698f7dac1eb6) with security fixes to this new branch.
3. Update xterm dependency in our package.json (teleport/gravity)
